### PR TITLE
Remove use of deprecated RAJA::loop_*

### PR DESCRIPTION
**Pull request by white238**
As stated in title...

### CODE REVIEW

**Review by kennyweiss — APPROVED** [review]
Thanks @white238 !

**Comment by kennyweiss** [comment]
Actually, on second thought, should we hold off merging this one until after several known users are able to upgrade beyond `raja@2022.10` ?

**Comment by kennyweiss** [comment]
Thanks!

**Review by rhornung67 — APPROVED** [review]

**Review by BradWhitlock — APPROVED** [review]
Looks good to me.

**Pull request merged**
