### PR TITLE
Add method to import Node holding array data into a View

### PR DESCRIPTION
**Pull request by nselliott**
# Summary

- This PR is a refactoring
- It does the following (modify list as needed):
  - Refactors code that was in `Group::importConduitTree` to create a standalone method to import a Node holding an array into a View

As I have been working on some SPIO changes to deal with changes to the Blueprint index, I found the need to import a Node that had a simple array of integers into a View that would hold a copy of that array in an internal attached Buffer.  `importConduitTree` has the code to do this, but it only works when the array Node is a leaf in a larger tree of hierarchical conduit data, and Sidre did not provide a method to do this operation by itself.

This PR refactors the existing code that did this task in `importConduitTree` into a standalone method `importArrayNode`.

### CODE REVIEW

**Review by cyrush — COMMENTED** [review]
Looks good, should there be a new (direct) test for `importArrayNode` ?

**Review by rhornung67 — CHANGES_REQUESTED** [review]
Looks good @nselliott I agree with @cyrush that a test should be added for the new method.

**Comment by nselliott** [comment]
Yes, it is exercised by several tests that call `importConduitTree` but a unit test is appropriate as well.

**Comment by nselliott** [comment]
I added a test with the last commit.  I can't parse the gitlab CI failure.

**Comment by rhornung67** [comment]
@nselliott it looks like the log output wasn't written to a file or it's looking for a file with another name. I'll try restarting that check.

**Review by agcapps — APPROVED** [review]
Thanks for adding the test, @nselliott .

**Review by rhornung67 — APPROVED** [review]
Thanks for the test. I pulled it the latest develop changes so it can be merged. When checks pass, feel free to merge.

**Pull request merged**
