### PR TITLE
Handle SLURM update

### PR DESCRIPTION
**Pull request by white238**
Props to @adrienbernede

### CODE REVIEW

**Review by kennyweiss — APPROVED** [review]
Enthusiastic 👍 

Thanks @white238  and @adrienbernede.
(Weird -- (I thought) that was the first thing I tried).

**Comment by adrienbernede** [comment]
From the logs on ruby, it seems the jobs are not reusing the pre-allocated resource:
```
[32;1m$ ${ALLOC_COMMAND} python3 scripts/llnl_scripts/build_src.py -v --host-config ${HOST_CONFIG} --extra-cmake-options -DENABLE_DOCS=OFF[0;m
srun: job 2699928 queued and waiting for resources
srun: job 2699928 has been allocated resources
```

**Review by adrienbernede — APPROVED** [review]

**Comment by adrienbernede** [comment]
@kennyweiss There should not be any srun message, those are here because there is an allocation actually being requested.

`ALLOC_COMMAND` is defined in `variables:` and _might_ be evaluate before the scripts starts, hence before the `ASSIGN_ID` variable is assigned a value.

**Comment by adrienbernede** [comment]
Looking from `variables` in the table here (https://docs.gitlab.com/ee/ci/variables/where_variables_can_be_used.html#gitlab-runner-internal-variable-expansion-mechanism), you can see how expansion is operated.

If I understand correctly, variables expansion in the `variables:` section does not support variables from scripts per:
https://docs.gitlab.com/ee/ci/variables/where_variables_can_be_used.html#gitlab-runner-internal-variable-expansion-mechanism

**Comment by adrienbernede** [comment]
Currently trying to find a solution working with your modular design.

**Review by rhornung67 — APPROVED** [review]
Thanks @adrienbernede I hope this fixes the issue.

**Comment by adrienbernede** [comment]
Per the tests, this fixes the issue. We are discussing a pre-existing issue that is causing sub-optimal use of resource.

**Comment by white238** [comment]
I am going to merge this PR because it unblocks us.  Then we can do a follow up PR to fix the alloc problem.

**Pull request merged**
