### PR TITLE
Update copyright to point to LICENSE file

### LINKED ISSUE #228: Fix Typo in Axom copyright
All of our files have the following copyright:
```
// Copyright (c) 2017-2020, Lawrence Livermore National Security, LLC and
// other Axom Project Developers. See the top-level COPYRIGHT file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
```

However, the **top-level COPYRIGHT** file does not exist. 

The text should probably say "See **top-level LICENSE** file for details" instead.

`sed` is your friend....

### PR DESCRIPTION
**Pull request by white238**
Please review quickly for my own sanity....

closes #228

### CODE REVIEW

**Review by cyrush — APPROVED** [review]
LGTC

You have the `LICENSE` to merge!

**Review by cyrush — APPROVED** [review]
LGTC

You have the `LICENSE` to merge!

**Review by agcapps — APPROVED** [review]
thank you CHRIS

**Review by kennyweiss — APPROVED** [review]

**Comment by white238** [comment]
I'm kind of at a loss why the ruby account is no longer working.  It definitely worked on the previous PR.  Did something change on the machine?

**Pull request merged**
