### PR TITLE
Reuse FESpace/QSpaces with same basis in MFEMSidreDataCollection

### LINKED ISSUE #533: Avoid duplicating MFEM FESpaces/QSpaces with the same basis name
Potential future optimization: Should `m_quadspaces` be a map from string name to `QuadratureSpace`? 
(This would need to be unique for each mesh, but `MFEMSidreDataCollection` is only over a single mesh)

_Originally posted by @kennyweiss in https://github.com/LLNL/axom/pull/433#discussion_r625478060_

### PR DESCRIPTION
**Pull request by joshessman-llnl**
# Summary

- This PR is a refactoring
- It does the following (modify list as needed):
  - Modifies `MFEMSidreDataCollection` to reuse FESpace/QSpace objects with the same basis
  - Fixes #533

### CODE REVIEW

**Review by kennyweiss — APPROVED** [review]
Thanks @joshessman-llnl !

My only minor concern is about whether we'll need to distinguish between `FESpace`s associated with the `mesh` and those associated with the `boundary_mesh`. Probably not an actual concern since I don't think we currently have a `RegisterBoundaryField`

**Review by rcarson3 — APPROVED** [review]
Nice work @joshessman-llnl ! This should definitely help reduce memory usage when several quadfuncs and gridfuncs share the same qspace and fespace and are saved off and then restored :)

**Comment by joshessman-llnl** [comment]
> 
> My only minor concern is about whether we'll need to distinguish between `FESpace`s associated with the `mesh` and those associated with the `boundary_mesh`. Probably not an actual concern since I don't think we currently have a `RegisterBoundaryField`

Right now we hardcode the association:

https://github.com/LLNL/axom/blob/3fd0dcef99ed50fc4aa8f6531bd1d4f0d906d240/src/axom/sidre/core/MFEMSidreDataCollection.cpp#L1229-L1232

Do you anticipate needing the ability to register boundary fields? [`mfem::DataCollection`](https://mfem.github.io/doxygen/html/classmfem_1_1DataCollection.html) doesn't expose this interface either but I can create Axom/MFEM issues for this if that functionality would be useful.

**Comment by kennyweiss** [comment]
> Do you anticipate needing the ability to register boundary fields? 

We might need to in the future, but let's hold off on thinking about it until there's an actual need.

**Review by white238 — APPROVED** [review]

**Review by rhornung67 — APPROVED** [review]

**Pull request merged**
