### PR TITLE
Initial check-in of github actions from serac.

### PR DESCRIPTION
**Pull request by hennis1**
# Summary

- This PR is a (refactoring, bugfix, feature, something else)
- It does the following (modify list as needed):
  - Modifies/refactors (class or method) (how?)
  - Fixes (issue number(s))
  - Adds (specific feature) at the request of (project or person)

### CODE REVIEW

**Comment by hennis1** [comment]
@white238 While I tried to make my own branch and just push it, the github didn't show up. github made me create this PR when I clicked on action.

**Comment by white238** [comment]
I should have read your last sentence better. I think this might not trigger Github actions to be created until it hits the default branch on github which is develop.

**Comment by white238** [comment]
Could you just rename the `main.yml` to `docker_build_tps.yml`?  I don't think you need to create a new branch.  I think/hope github will auto-detect the file once merged into `develop`.

**Comment by white238** [comment]
My hello world one is now showing up.  Try rebasing on develop, maybe github will figure it out because mine is now there.  Who knows.

**Comment by white238** [comment]
Closed for new branch

**Pull request closed without merging**
