### PR TITLE
Added mfem to gcc8 and clang10 dockers

### PR DESCRIPTION
**Pull request by hennis1**
# Summary

- This PR is for adding the mfem feature to the docker containers.
- It does the following (modify list as needed):
  - Adds mfem to the docker containers

### CODE REVIEW

**Review by rhornung67 — APPROVED** [review]
I'm good with this if @white238 is. Thanks @hennis1 👍

**Comment by white238** [comment]
Were you doing just +mfem in this PR or were you trying to update gfortran and CMake here as well? I am okay with leaving CMake at the current version because we test against newer versions on LC.  It may not be worth updating it here...

**Comment by hennis1** [comment]
> Were you doing just +mfem in this PR or were you trying to update gfortran and CMake here as well? I am okay with leaving CMake at the current version because we test against newer versions on LC. It may not be worth updating it here...

gfortran and cmake are in other branches and aren't working. I am keeping them separate. Is there any dependency on mfem for gfortran or cmake?

**Comment by white238** [comment]
You need to update the azure-pipelines.yml to the new docker image names with the time date stamp in them.  It should be in the build logs I think.

**Review by white238 — APPROVED** [review]
Looks great! Thanks @hennis1 !

**Review by rhornung67 — APPROVED** [review]
Thanks a bunch @hennis1

**Pull request merged**
