### PR TITLE
Fleshing out axom::Array support

### PR DESCRIPTION
**Pull request by kanye-quest**
# Summary

- Adds support for calling `Array<T>` functions `set()`, `emplace()/emplace_back()`, and `insert()/push_back()` when `Array<T>` is allocated in device-only memory
  - This completes host-side support for all outstanding `Array<T>` functions on device-only memory
- Refactors `detail::ArrayOps<T>`
  - Helper functions are now encapsulated in an `ArrayOpsBase<T, bool>` class: `ArrayOpsBase<T, false>` implements helper functions for CPU-accessible memory, while `ArrayOpsBase<T, true>` implements helper functions for device-only memory.
  - SFINAE on member operations in `ArrayOpsBase` is used to handle differences in implementations depending on type traits like `is_trivially_copy_constructible`/`is_default_constructible`
- Replaces use of `std::is_trivial<T>` with more-specific type traits
  - Adds macro check to switch to TR1-based fallback for `std::is_trivially_copy_constructible`, which isn't implemented for GCC 4.9.3's libstdc++
 - Adds missing `std::forward`s in some uses in `Array<T>::emplace()`

### CODE REVIEW

**Review by kennyweiss — APPROVED** [review]
Thanks @kanye-quest -- this is great!

**Review by agcapps — APPROVED** [review]
Thanks, @kanye-quest

**Comment by rhornung67** [comment]
@kanye-quest I think we should ignore gcc 4.9.3 since the upcoming RAJA and Umpire releases will require C++14.

**Review by rhornung67 — APPROVED** [review]

**Comment by kennyweiss** [comment]
> @kanye-quest I think we should ignore gcc 4.9.3 since the upcoming RAJA and Umpire releases will require C++14.

Unfortunately, some of our user codes still have `gcc@4.9.3` as their std library behind intel and/or clang, so the fixes for gcc@4.9.3 are still helpful and appreciated.

**Pull request merged**
