### PR TITLE
Task/white238/axomdevpurge

### PR DESCRIPTION
**Pull request by white238**
* Gets rid of axomdev group
* Fixes a lot of the llnl scripts
* Remove references to old paths and machines

### CODE REVIEW

**Review by agcapps — APPROVED** [review]
Thank you for the solid work, @white238 .

**Comment by white238** [comment]
LGTM

**Review by kennyweiss — APPROVED** [review]
Thanks @white238 -- this is great!

**Comment by white238** [comment]
LGTM

**Pull request merged**
