### PR TITLE
Playing with jobs

### PR DESCRIPTION
**Pull request by rhornung67**

### CODE REVIEW

**Comment by cyrush** [comment]
looks like you are converging, looks nice if the templates work out this way

**Comment by rhornung67** [comment]
I don't think templates are the right thing to use here.  I'm trying to understand how this works. I'm stuck on how to conditionally perform step sequences... DevOps docs are not very clear, to me at least...

**Comment by cyrush** [comment]
wishful thinking on my part, what were approaching for looked sensible :-)

**Comment by rhornung67** [comment]
I think I'm on to something.... 🙉

**Comment by cyrush** [comment]
we are counting on you 🙀

**Comment by rhornung67** [comment]
Then, all is lost. We still need to build docker images for our tpl sets so we can test everything. I don't really know where to start there.... 💩

**Comment by rhornung67** [comment]
pointing and clicking on the path to destruction 🚯

**Pull request closed without merging**
