### PR TITLE
Change links to docs to (hopefully) reach project-wide detent

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary

- This PR changes the RTD links in the README file to hopefully reach project-wide detente on this topic.

### CODE REVIEW

**Review by kennyweiss — APPROVED** [review]

**Review by agcapps — APPROVED** [review]
Looks great!

**Comment by white238** [comment]
https://axom.readthedocs.io/en/task-doc-links/

**Comment by white238** [comment]
lol... i dont know why i built that.

**Review by white238 — APPROVED** [review]

**Comment by rhornung67** [comment]
So @white238 this works for you?  This way, we don't have to change README.md when the version changes.

**Comment by rhornung67** [comment]
LGTM

**Pull request merged**
