### PR TITLE
Include cstdint

### LINKED ISSUE #1272: Include <cstdint> for higher GCC versions
Newer versions of GCC require including `cstdint` explicitly in order to use `std::uint32_t` and similar types. It will need to be added to this file:

https://github.com/LLNL/axom/blob/develop/src/axom/core/utilities/nvtx/interface.hpp

I can create a PR for this soon.

This was hit by mfem recently as well: https://github.com/mfem/mfem/commit/19f30e814dc2846dd5ab8e827477d3da34b35d8d

### PR DESCRIPTION
**Pull request by chapman39**
# Summary

- This PR is a bugfix,
- It does the following:
  - Includes cstdint for higher gcc version support (e.g. gcc-13)
  - Fixes #1272

### CODE REVIEW

**Review by kennyweiss — APPROVED** [review]
Thanks @chapman39 !

**Review by kennyweiss — APPROVED** [review]
Thanks @chapman39 !

**Review by rhornung67 — APPROVED** [review]
@chapman39 thank you for the contribution!

**Comment by white238** [comment]
The codes have spoken... ROCM 5.4.3 isnt needed and it is what is causing the pipeline issues. I have turned it off.

**Pull request merged**
