### PR TITLE
Update sparsehash headers to v. 2.0.4

### PR DESCRIPTION
**Pull request by nselliott**
# Summary

- This PR is a third-party library update
- It does the following (modify list as needed):
  - Brings in headers from sparsehash v. 2.0.4.  The code changes come from that library, not from our team.
  - Addresses comment from @rhornung67 in issue #365 but does not address the original user issue.

### CODE REVIEW

**Review by rhornung67 — APPROVED** [review]
Looks good. Please add an entry for this in the release notes file.

**Review by agcapps — APPROVED** [review]
Thanks @nselliott .

**Comment by kennyweiss** [comment]
@nselliott  -- will we still need the following patch -- `sparsehash-2.0.3-no-tr1.patch`  ?
Or should it be removed as part of this PR?

See: https://github.com/LLNL/axom/tree/develop/src/thirdparty/patches

**Comment by nselliott** [comment]
While I'm in the release notes, I'll also add an entry for the recent conduit update, since I neglected to do that at the time.

**Review by kennyweiss — APPROVED** [review]

**Comment by nselliott** [comment]
> 
> 
> @nselliott -- will we still need the following patch -- `sparsehash-2.0.3-no-tr1.patch` ?
> Or should it be removed as part of this PR?
> 
> See: https://github.com/LLNL/axom/tree/develop/src/thirdparty/patches

@kennyweiss I think that patch was made obsolete by this commit.  https://github.com/LLNL/axom/commit/053e33c6604cfb0873ba162c9ca08c4ddefd3adb ;  I believe before you added this, we were finding the tr1 header by default even when the standard `<functional>` was present.  Now C++ 11 and later compilers should always find the `<functional>` header and never need to worry about the tr1 stuff.  Does that sound correct @agcapps ?

**Comment by kennyweiss** [comment]
Thanks @nselliott.  If so, I'd suggest removing that patch file.

**Comment by agcapps** [comment]
> 
> 
> > @nselliott -- will we still need the following patch -- `sparsehash-2.0.3-no-tr1.patch` ?
> > Or should it be removed as part of this PR?
> > See: https://github.com/LLNL/axom/tree/develop/src/thirdparty/patches
> 
> @kennyweiss I think that patch was made obsolete by this commit. [053e33c](https://github.com/LLNL/axom/commit/053e33c6604cfb0873ba162c9ca08c4ddefd3adb) ; I believe before you added this, we were finding the tr1 header by default even when the standard `<functional>` was present. Now C++ 11 and later compilers should always find the `<functional>` header and never need to worry about the tr1 stuff. Does that sound correct @agcapps ?

That does sound correct.

**Pull request merged**
