### PR TITLE
Main into develop for v0.5.0

### PR DESCRIPTION
**Pull request by ltaylor16**
# Merge main branch back into develop

- This PR is a part of the release of v0.5.0
- Merge changes made as part of the release candidate into develop.

### CODE REVIEW

**Review by white238 — APPROVED** [review]

**Review by kennyweiss — CHANGES_REQUESTED** [review]
@ltaylor16 -- did you update the version to 0.5.0?

I looked at `AxomVersion.cmake` and didn't see the change
See: https://github.com/LLNL/axom/blob/main/src/cmake/AxomVersion.cmake

I think we also have to update the `RELEASE` file:
https://github.com/LLNL/axom/blob/main/RELEASE


If not, I think you'll need to create a PR into main to fix this.

**Comment by ltaylor16** [comment]
Created #558 to update the files.  Then I'll delete the release and run it again.

**Comment by white238** [comment]
> 
> 
> @ltaylor16 -- did you update the version to 0.5.0?
> 
> I looked at `AxomVersion.cmake` and didn't see the change
> See: https://github.com/LLNL/axom/blob/main/src/cmake/AxomVersion.cmake
> 
> I think we also have to update the `RELEASE` file:
> https://github.com/LLNL/axom/blob/main/RELEASE
> 
> If not, I think you'll need to create a PR into main to fix this.
> 
> The process is described here: https://github.com/LLNL/axom/blob/8208dfaa4267e2cab6fb673151c3064a2cc9837a/src/docs/sphinx/dev_guide/release.rst#2-issue-a-pull-request
> 
> Sorry I missed it before.

Also the

**Review by kennyweiss — APPROVED** [review]
Approving so this doesn't hold you up.

(I'm assuming this will merge after #558)

**Comment by ltaylor16** [comment]
> 
> 
> > @ltaylor16 -- did you update the version to 0.5.0?
> > I looked at `AxomVersion.cmake` and didn't see the change
> > See: https://github.com/LLNL/axom/blob/main/src/cmake/AxomVersion.cmake
> > I think we also have to update the `RELEASE` file:
> > https://github.com/LLNL/axom/blob/main/RELEASE
> > If not, I think you'll need to create a PR into main to fix this.
> > The process is described here: https://github.com/LLNL/axom/blob/8208dfaa4267e2cab6fb673151c3064a2cc9837a/src/docs/sphinx/dev_guide/release.rst#2-issue-a-pull-request
> > Sorry I missed it before.
> 
> Also the

Also the what?

I've merged #558, deleted the release, deleted the v0.5.0 tag, created a new release (which creates v0.5.0 tag), created tar files and uploaded to release.  I think we're all set.

**Comment by white238** [comment]
sorry! i misclicked thanks again!

**Review by rhornung67 — APPROVED** [review]
There was a lot of activity yesterday getting the release out. I wasn't able to follow as I was in meetings. Thanks everyone!

**Review by agcapps — APPROVED** [review]
Thanks for this Lee.

**Pull request merged**
