### PR TITLE
Add new schema to generated Blueprint index

### PR DESCRIPTION
**Pull request by nselliott**
# Summary

- This PR is a feature
- It does the following (modify list as needed):
  - Adds new data to SPIO's generated Blueprint index following the `partition_pattern` and `partition_map` schemas described in the comments of https://github.com/LLNL/conduit/issues/476
  - Uses conduit's new `generate_domain_to_rank_map` and implements `IOManager::getRankToFileMap` to compute the needed map arrays.

### CODE REVIEW

**Review by rhornung67 — APPROVED** [review]
Question: have we changes the code format guidelines to use "if(...)" (no space between 'if' and paren) from "if (...)" (space between 'if' and paren)?  All of the if conditionals in this change use the former.

**Comment by nselliott** [comment]
@rhornung67 That is what clangformat produces currently.

**Comment by rhornung67** [comment]
> @rhornung67 That is what clangformat produces currently.

OK. Thanks. I'll bring this up at the meeting next Monday.

**Comment by kennyweiss** [comment]
@nselliott  and @cyrush -- Do you know which version of `conduit` this PR requires?  Is is `v0.7.2` or something earlier?

Please add a note to the README stating this requirement.

**Comment by nselliott** [comment]
@kennyweiss It requires 0.7.2.  Do you mean the RELEASE-NOTES?

**Review by kennyweiss — APPROVED** [review]
Thanks @nselliott !

**Review by cyrush — APPROVED** [review]

**Review by agcapps — APPROVED** [review]

**Pull request merged**
