### PR TITLE
Update fmt to 7.1.3

### PR DESCRIPTION
**Pull request by white238**
Updates fmt to the newest release which is 7.1.3 (Nov 24, 2020)

### CODE REVIEW

**Comment by white238** [comment]
Running it through all specs on rzgenie and rzansel...

**Review by kennyweiss — APPROVED** [review]
Thanks @white238!

**Review by agcapps — APPROVED** [review]
Thanks, @white238 .

**Review by rhornung67 — APPROVED** [review]
Thanks, @white238

**Review by cyrush — APPROVED** [review]

**Comment by white238** [comment]
There is a problem with fmt and intel 18.  I will look into it before merging this PR.

**Comment by white238** [comment]
Everything works except for one test on intel@18 and only a very specific functionality that we don't use except for in the one test.

The following test core dumps:

https://github.com/LLNL/axom/blob/develop/src/axom/slic/tests/slic_fmt.cpp

I simplified the failing test down to this:

```
#include "axom/config.hpp"
#include "fmt/fmt.hpp"

#include <iostream>

int main()
{
  std::string s = fmt::format("Hello, {name}! Goodbye, {name}.", fmt::arg("name", "ASC Toolkit"));
  std::cout << s << std::endl;

  return 0;
}
```

Thoughts, @rhornung67 , @cyrush , @kennyweiss ?

**Comment by rhornung67** [comment]
Let's #ifdef this test out for intel 18.

**Pull request merged**
