### PR TITLE
Update config.yaml to modern spec.format syntax

### PR DESCRIPTION
**Pull request by becker33**
This should eliminate warnings from newer versions of Spack

### CODE REVIEW

**Comment by becker33** [comment]
@cyrush @white238 @kennyweiss as discussed in our meeting

**Review by kennyweiss — APPROVED** [review]
Thanks @becker33 !

**Comment by becker33** [comment]
I found a second file that requires the same changes. I think that's going to be all of them though, I searched for `${PACKAGE}` in the whole repo and didn't find anything else.

**Review by rhornung67 — APPROVED** [review]
Thank you @becker33

**Review by white238 — APPROVED** [review]
Thanks @becker33 . I pushed to the Serac repo too.

**Pull request merged**
