### PR TITLE
Attempt to fix the full build jobs

### PR DESCRIPTION
**Pull request by white238**
The gitlab ci that runs after you merge to develop or main has been broken.  This fixes at least the following problem:

```
You do not have the initial commit yet
From https://github.com/spack/spack
 * branch            764c17053041a65f684ce565a2598d705b04a16b -> FETCH_HEAD
fatal: Unable to create '/usr/WS2/white238/gitlabbuilds/axom_tpls/170/blueos_3_ppc64le_ib_p9/2021_04_13_11_53_02/spack/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

### CODE REVIEW

**Review by kennyweiss — APPROVED** [review]
Thanks @white238 !

**Review by agcapps — APPROVED** [review]
Thank you Chris.

**Review by rhornung67 — APPROVED** [review]

**Comment by white238** [comment]
I am going to try to rejigger this more.  I would like the src workflow to run on PRs and merges to develop/main then change the full build to be nightly. This requires me to test it in a testbed and will come in later.

**Comment by rhornung67** [comment]
> I am going to try to rejigger this more. I would like the src workflow to run on PRs and merges to develop/main then change the full build to be nightly. This requires me to test it in a testbed and will come in later.

Sounds like a good plan. 👍

**Comment by white238** [comment]
This triggering mechanism has been tested in Serac.  This at least works where src will now build on all branch changes due to the mirroring.

I think the regular "CI -> Schedules" option will allow us to do the nightly builds on our protected branches.

**Pull request merged**
