### PR TITLE
Add artifacting of test output

### PR DESCRIPTION
**Pull request by white238**

### CODE REVIEW

**Comment by white238** [comment]
LGTM

**Review by agcapps — APPROVED** [review]
Thumbs up

**Review by kennyweiss — APPROVED** [review]
Thanks @white238 

Is there a way to separate the config, build and test artifacts into separate files? Or is that just not how it works.

**Comment by white238** [comment]
You can add any file as an artifact..  I'll figure out the paths later.

**Comment by white238** [comment]
LGTM

**Comment by white238** [comment]
Added all log output and newly converted CTest (to JUnit) output.  They can now be found in various places in gitlab.

**Pull request merged**
