### PR TITLE
Fix Sidre failures on blueos

### PR DESCRIPTION
**Pull request by white238**
Thanks to @davidbeckingsale for pointing out the fix.

Rzmanta host-configs coming soon then it will be okay to merge.

### CODE REVIEW

**Review by kennyweiss — APPROVED** [review]
Thanks @white238  and @davidbeckingsale !

**Comment by white238** [comment]
spin_bvh is failing for another reason:

```
CUDAassert: peer access is not supported between these two devices /usr/WS1/axom/libs/blueos_3_ppc64le_ib/2020_12_07_21_02_19/xl-16.1.1_nvcc/raja-0.12.1/include/RAJA/policy/cuda/sort.hpp 341
unknown file: Failure
```

**Comment by rhornung67** [comment]
> spin_bvh is failing for another reason:
> 
> ```
> CUDAassert: peer access is not supported between these two devices /usr/WS1/axom/libs/blueos_3_ppc64le_ib/2020_12_07_21_02_19/xl-16.1.1_nvcc/raja-0.12.1/include/RAJA/policy/cuda/sort.hpp 341
> unknown file: Failure
> ```

Is a RAJA sort method being called inside device code? We've talked about doing that, but don't support it yet.

**Comment by davidbeckingsale** [comment]
Are you allocating on one GPU with Umpire and then trying to run on a different one?

**Comment by white238** [comment]
> > spin_bvh is failing for another reason:
> > ```
> > CUDAassert: peer access is not supported between these two devices /usr/WS1/axom/libs/blueos_3_ppc64le_ib/2020_12_07_21_02_19/xl-16.1.1_nvcc/raja-0.12.1/include/RAJA/policy/cuda/sort.hpp 341
> > unknown file: Failure
> > ```
> 
> This looks like it is trying to use a different device than the default. Does this work with manual test runs; i.e., outside of Gitlab CI?

Fails when i run it manually

**Comment by white238** [comment]
I would like to get this PR in since it fixes all but spin_bvh and I don't know how long that one is going to take.

**Comment by kennyweiss** [comment]
Thanks @white238  -- I agree that it would be good to get this one in now since it solves one of the issues.  We can follow up with a follow-up PR to resolve the `rzmanta` issue.

**Review by agcapps — APPROVED** [review]
Thank you for putting this in, @white238 .

**Pull request merged**
