### PR TITLE
The Great Spack Package Merge of 2024

### PR DESCRIPTION
**Pull request by white238**
I built this successfully on all platforms but there is no change in libraries so I am not updating host-configs.

### CODE REVIEW

**Comment by white238** [comment]
https://github.com/spack/spack/pull/42269

**Comment by ltaylor16** [comment]
I plan on updating the `spack_commit` version in `scripts/spack/devtools.json` as part of #1258. It is behind `.uberenv_config.json` and I assume they should match.

**Comment by white238** [comment]
> I plan on updating the `spack_commit` version in `scripts/spack/devtools.json` as part of #1258. It is behind `.uberenv_config.json` and I assume they should match.

They should match but sometimes cannot due to running into bugs.

**Review by kennyweiss — APPROVED** [review]
Thanks @white238.

After this and the spack PRs merge, is the `c2c` dependency the only difference b/w this file and the axom package in spack?

**Comment by white238** [comment]
> Thanks @white238.
> 
> After this and the spack PRs merge, is the `c2c` dependency the only difference b/w this file and the axom package in spack?

yes.

**Review by bmhan12 — APPROVED** [review]

**Pull request merged**
